#! /bin/bash
cd /home/jamil/ProyectoLenguajes2/src/
jlex *.lex
echo "-- Archivos Lexicos procesados --"
cup -expect 5 Leng2.cup
echo "-- Leng2.cup procesado --"
cup -parser preparser -symbols presymbol -expect 5 PreLeng2.cup
echo "-- PreLeng2.cup procesado --"
#javac *.java
