
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 03 12:57:30 VET 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class presymbol {
  /* terminals */
  public static final int REGISTRO = 17;
  public static final int DOSPUNTOS = 9;
  public static final int CASO = 19;
  public static final int POR = 29;
  public static final int OLOG = 37;
  public static final int ENTSAL = 7;
  public static final int DECLENTERO = 12;
  public static final int ENTERO = 54;
  public static final int SI = 46;
  public static final int CIERTO = 52;
  public static final int YLOG = 36;
  public static final int FINFUNC = 3;
  public static final int TECHO = 33;
  public static final int FIN = 11;
  public static final int MENORIGUAL = 44;
  public static final int COMIENZO = 10;
  public static final int IGUAL = 39;
  public static final int SINO = 47;
  public static final int FINPROC = 5;
  public static final int FINREG = 18;
  public static final int DIV = 31;
  public static final int ID = 55;
  public static final int PISO = 34;
  public static final int PYCOMA = 51;
  public static final int MAYORIGUAL = 43;
  public static final int EOF = 0;
  public static final int ACORCH = 23;
  public static final int error = 1;
  public static final int CCORCH = 24;
  public static final int COMA = 25;
  public static final int DIF = 40;
  public static final int TIPODATO = 15;
  public static final int MENOS = 28;
  public static final int MENOR = 42;
  public static final int MOD = 32;
  public static final int ES = 20;
  public static final int DECLBOOL = 14;
  public static final int ASIGNACION = 45;
  public static final int REAL = 56;
  public static final int MAYOR = 41;
  public static final int ENTRADA = 6;
  public static final int PUNTO = 26;
  public static final int FUNC = 2;
  public static final int NOLOG = 38;
  public static final int FINHACER = 50;
  public static final int FALSO = 53;
  public static final int HACER = 49;
  public static final int PROC = 4;
  public static final int REDONDEO = 35;
  public static final int FINSI = 48;
  public static final int DECLREAL = 13;
  public static final int SALIDA = 8;
  public static final int ENTRE = 30;
  public static final int FINT = 16;
  public static final int APARENT = 21;
  public static final int CPARENT = 22;
  public static final int MAS = 27;
}

