
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 07 06:28:50 VET 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class presymbol {
  /* terminals */
  public static final int DOSPUNTOS = 10;
  public static final int POR = 23;
  public static final int ENTSAL = 8;
  public static final int OLOG = 31;
  public static final int DECLENTERO = 13;
  public static final int ENTERO = 50;
  public static final int SI = 40;
  public static final int CIERTO = 48;
  public static final int YLOG = 30;
  public static final int FINFUNC = 4;
  public static final int TECHO = 27;
  public static final int FIN = 12;
  public static final int MENORIGUAL = 38;
  public static final int COMIENZO = 11;
  public static final int IGUAL = 33;
  public static final int SINO = 41;
  public static final int FINPROC = 6;
  public static final int ESCRIBIR = 45;
  public static final int DIV = 25;
  public static final int ID = 51;
  public static final int PISO = 28;
  public static final int PYCOMA = 47;
  public static final int MAYORIGUAL = 37;
  public static final int EOF = 0;
  public static final int ACORCH = 18;
  public static final int error = 1;
  public static final int CCORCH = 19;
  public static final int COMA = 20;
  public static final int DIF = 34;
  public static final int MENOS = 22;
  public static final int MENOR = 36;
  public static final int MOD = 26;
  public static final int IDENT = 2;
  public static final int DECLBOOL = 15;
  public static final int ASIGNACION = 39;
  public static final int REAL = 52;
  public static final int MAYOR = 35;
  public static final int ENTRADA = 7;
  public static final int FUNC = 3;
  public static final int NOLOG = 32;
  public static final int FINHACER = 44;
  public static final int FALSO = 49;
  public static final int LEER = 46;
  public static final int HACER = 43;
  public static final int PROC = 5;
  public static final int REDONDEO = 29;
  public static final int FINSI = 42;
  public static final int DECLREAL = 14;
  public static final int SALIDA = 9;
  public static final int ENTRE = 24;
  public static final int APARENT = 16;
  public static final int CPARENT = 17;
  public static final int MAS = 21;
}

