
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 06 01:05:41 VET 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 38;
  public static final int POR = 11;
  public static final int OLOG = 19;
  public static final int DECLENTERO = 4;
  public static final int SI = 28;
  public static final int CIERTO = 36;
  public static final int YLOG = 18;
  public static final int TECHO = 15;
  public static final int FIN = 3;
  public static final int MENORIGUAL = 26;
  public static final int COMIENZO = 2;
  public static final int IGUAL = 21;
  public static final int SINO = 29;
  public static final int ESCRIBIR = 33;
  public static final int DIV = 13;
  public static final int ID = 39;
  public static final int PISO = 16;
  public static final int PYCOMA = 35;
  public static final int MAYORIGUAL = 25;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int DIF = 22;
  public static final int MENOS = 10;
  public static final int MENOR = 24;
  public static final int MOD = 14;
  public static final int DECLBOOL = 6;
  public static final int ASIGNACION = 27;
  public static final int REAL = 40;
  public static final int MAYOR = 23;
  public static final int NOLOG = 20;
  public static final int FINHACER = 32;
  public static final int REDONDEAR = 17;
  public static final int FALSO = 37;
  public static final int LEER = 34;
  public static final int HACER = 31;
  public static final int FINSI = 30;
  public static final int DECLREAL = 5;
  public static final int ENTRE = 12;
  public static final int APARENT = 7;
  public static final int CPARENT = 8;
  public static final int MAS = 9;
}

