
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 12 19:28:41 CDT 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 9;
  public static final int CASO = 18;
  public static final int POR = 28;
  public static final int OLOG = 36;
  public static final int ENTSAL = 7;
  public static final int DECLENTERO = 12;
  public static final int ENTERO = 53;
  public static final int SI = 45;
  public static final int CIERTO = 51;
  public static final int YLOG = 35;
  public static final int FINFUNC = 3;
  public static final int TECHO = 32;
  public static final int FIN = 11;
  public static final int MENORIGUAL = 43;
  public static final int COMIENZO = 10;
  public static final int IGUAL = 38;
  public static final int SINO = 46;
  public static final int FINPROC = 5;
  public static final int DIV = 30;
  public static final int ID = 54;
  public static final int PISO = 33;
  public static final int PYCOMA = 50;
  public static final int MAYORIGUAL = 42;
  public static final int EOF = 0;
  public static final int ACORCH = 22;
  public static final int FINTIPODATO = 16;
  public static final int error = 1;
  public static final int CCORCH = 23;
  public static final int COMA = 24;
  public static final int DIF = 39;
  public static final int TIPODATO = 15;
  public static final int MENOS = 27;
  public static final int MENOR = 41;
  public static final int MOD = 31;
  public static final int ES = 19;
  public static final int DECLBOOL = 14;
  public static final int ASIGNACION = 44;
  public static final int REAL = 55;
  public static final int MAYOR = 40;
  public static final int ENTRADA = 6;
  public static final int PUNTO = 25;
  public static final int FUNC = 2;
  public static final int NOLOG = 37;
  public static final int FINHACER = 49;
  public static final int FALSO = 52;
  public static final int HACER = 48;
  public static final int PROC = 4;
  public static final int REDONDEO = 34;
  public static final int FINSI = 47;
  public static final int DECLREAL = 13;
  public static final int SALIDA = 8;
  public static final int ENTRE = 29;
  public static final int FINT = 17;
  public static final int APARENT = 20;
  public static final int CPARENT = 21;
  public static final int MAS = 26;
}

