
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 04 19:42:18 VET 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 9;
  public static final int CASO = 17;
  public static final int POR = 27;
  public static final int OLOG = 35;
  public static final int ENTSAL = 7;
  public static final int DECLENTERO = 12;
  public static final int ENTERO = 52;
  public static final int SI = 44;
  public static final int CIERTO = 50;
  public static final int YLOG = 34;
  public static final int FINFUNC = 3;
  public static final int TECHO = 31;
  public static final int FIN = 11;
  public static final int MENORIGUAL = 42;
  public static final int COMIENZO = 10;
  public static final int IGUAL = 37;
  public static final int SINO = 45;
  public static final int FINPROC = 5;
  public static final int DIV = 29;
  public static final int ID = 53;
  public static final int PISO = 32;
  public static final int PYCOMA = 49;
  public static final int MAYORIGUAL = 41;
  public static final int EOF = 0;
  public static final int ACORCH = 21;
  public static final int error = 1;
  public static final int CCORCH = 22;
  public static final int COMA = 23;
  public static final int DIF = 38;
  public static final int TIPODATO = 15;
  public static final int MENOS = 26;
  public static final int MENOR = 40;
  public static final int MOD = 30;
  public static final int ES = 18;
  public static final int DECLBOOL = 14;
  public static final int ASIGNACION = 43;
  public static final int REAL = 54;
  public static final int MAYOR = 39;
  public static final int ENTRADA = 6;
  public static final int PUNTO = 24;
  public static final int FUNC = 2;
  public static final int NOLOG = 36;
  public static final int FINHACER = 48;
  public static final int FALSO = 51;
  public static final int HACER = 47;
  public static final int PROC = 4;
  public static final int REDONDEO = 33;
  public static final int FINSI = 46;
  public static final int DECLREAL = 13;
  public static final int SALIDA = 8;
  public static final int ENTRE = 28;
  public static final int FINT = 16;
  public static final int APARENT = 19;
  public static final int CPARENT = 20;
  public static final int MAS = 25;
}

